// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// constructNetwork
Rcpp::List constructNetwork(NumericVector out_strength, NumericVector in_strength, DataFrame df);
RcppExport SEXP _finetworks_constructNetwork(SEXP out_strengthSEXP, SEXP in_strengthSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type out_strength(out_strengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type in_strength(in_strengthSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(constructNetwork(out_strength, in_strength, df));
    return rcpp_result_gen;
END_RCPP
}
// constructMatrix
int constructMatrix(NumericVector rowSums, NumericVector colSums, DataFrame fixed);
RcppExport SEXP _finetworks_constructMatrix(SEXP rowSumsSEXP, SEXP colSumsSEXP, SEXP fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rowSums(rowSumsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type colSums(colSumsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type fixed(fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(constructMatrix(rowSums, colSums, fixed));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_graph_module();

static const R_CallMethodDef CallEntries[] = {
    {"_finetworks_constructNetwork", (DL_FUNC) &_finetworks_constructNetwork, 3},
    {"_finetworks_constructMatrix", (DL_FUNC) &_finetworks_constructMatrix, 3},
    {"_rcpp_module_boot_graph_module", (DL_FUNC) &_rcpp_module_boot_graph_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_finetworks(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
