# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

constructNetwork <- function(out_strength, in_strength, df) {
    .Call('_finetworks_constructNetwork', PACKAGE = 'finetworks', out_strength, in_strength, df)
}

